name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-validate:
    name: Lint and validate
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Install Dependencies
        run: task install:deps -y

      - name: Validate PSLiongard
        run: task validate

      - name: Lint
        run: task lint
